### PR TITLE
Update Glossary.md

### PR DESCRIPTION
**Pull request by coopsand**
Added a definition for Markdown.

### CODE REVIEW

**Review by Skye404 — CHANGES_REQUESTED** [review]
I like the added definition. The first letter after colons should all be either capitalized or lowercase. Be consistent. Also, I'm practicing with different ways to give feedback here, so I wanted to try the "request changes" feature.

**Comment by coopsand** [comment]
I believe that I went in and changed the casing. Let me know if you can't see it. :)

**Review by coopsand — COMMENTED** [review]
Fixed in new commit.

**Review by Skye404 — APPROVED** [review]
Looks good!

**Pull request merged**
