### PR TITLE
Update Week-09.md

### PR DESCRIPTION
**Pull request by Skye404**
added canvas rubric note for clarification of expectations

### CODE REVIEW

**Comment by coopsand** [comment]
If you allow me to approve this - I can approve and merge it. Also, Professor Duncan is no longer teaching the class, so he won't be able to review your posts for approval. The class is being taught by @kensnyder now. :)

**Review by coopsand — APPROVED** [review]
I was able to request myself as a reviewer. Great addition to the page.

**Comment by kensnyder** [comment]
Thanks @Skye404 and @coopsand.

**Comment by CJ3315** [comment]
Great addition! This was a smart idea!

**Pull request merged**
